name: Build And Push Container Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: unifi_exporter
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Buildx
      run: |
        docker buildx create --use
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64/v8 --tag ${{ env.REGISTRY }}/5hrz/${{ env.IMAGE_NAME }}:${{ github.ref_name }} --push .